# Generated by Django 2.2.3 on 2019-09-13 14:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(default=None, max_length=30)),
                ('middleName', models.CharField(blank=True, max_length=30, null=True)),
                ('lastName', models.CharField(default=None, max_length=30)),
                ('mobileNo', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('password', models.CharField(default=None, max_length=500)),
                ('emailAdd', models.EmailField(default=None, max_length=40)),
                ('experience', models.IntegerField(default=None)),
                ('age', models.IntegerField(default=None)),
                ('temporaryAddress', models.TextField(default=None, max_length=300)),
                ('tPincode', models.IntegerField(default=None)),
                ('permanentAddress', models.TextField(default=None, max_length=300)),
                ('pPincode', models.IntegerField(default=None)),
                ('gender', models.CharField(default=None, max_length=15)),
            ],
            options={
                'db_table': 'Admin information_Information',
            },
        ),
    ]
