# Generated by Django 2.2.3 on 2019-09-13 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employee',
            new_name='Admin',
        ),
    ]
