# Generated by Django 2.2.3 on 2019-09-14 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0002_auto_20190913_2220'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emailAdd', models.EmailField(default=None, max_length=40)),
                ('role', models.CharField(default=None, max_length=40)),
            ],
        ),
    ]
