# Generated by Django 2.2.3 on 2019-09-15 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0003_shopusers'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='shopusers',
            table='ShopUsers',
        ),
    ]
