# Generated by Django 2.2.3 on 2019-09-15 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0004_auto_20190915_1436'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='admin',
            table='Admin information',
        ),
    ]
