# Generated by Django 2.2.3 on 2019-09-07 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0003_customer_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='middleName',
            field=models.CharField(default='', max_length=30),
        ),
    ]
