# Generated by Django 2.2.3 on 2019-09-07 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0004_auto_20190907_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='middleName',
            field=models.CharField(blank=True, default=None, max_length=30),
        ),
    ]
