# Generated by Django 2.2.3 on 2019-09-11 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0007_auto_20190907_2223'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.CharField(default=None, max_length=1000)),
                ('emailAdd', models.EmailField(default=None, max_length=40)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Customer Feedbacks',
            },
        ),
    ]
