# Generated by Django 2.2.3 on 2019-09-07 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0002_employee_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='middleName',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
