# Generated by Django 2.2.3 on 2019-09-07 16:30

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0003_auto_20190907_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='mobileNo',
            field=phone_field.models.PhoneField(max_length=31),
        ),
    ]
