# Generated by Django 2.2.3 on 2019-09-07 16:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0004_auto_20190907_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='mobileNo',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
