# Generated by Django 2.2.3 on 2019-09-18 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0005_auto_20190907_2217'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'permissions': (('is_employee', 'can do employee task'),)},
        ),
    ]
