# Generated by Django 2.2.3 on 2019-09-18 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0006_auto_20190918_1841'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'permissions': [('is_employee', 'can do employee task')]},
        ),
    ]
