# Generated by Django 2.2.3 on 2019-07-14 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookId', models.IntegerField(max_length=10)),
                ('title', models.CharField(max_length=30)),
                ('isbn', models.CharField(max_length=15)),
                ('language', models.CharField(max_length=20)),
                ('publisher', models.CharField(max_length=30)),
                ('author', models.CharField(max_length=30)),
                ('mrp', models.IntegerField(max_length=5)),
                ('publishYear', models.CharField(max_length=4)),
                ('quantity', models.IntegerField(max_length=3)),
                ('description', models.CharField(max_length=300)),
                ('rating', models.IntegerField(max_length=1)),
            ],
            options={
                'db_table': 'Book Detailss',
            },
        ),
    ]
