# Generated by Django 2.2.3 on 2019-07-14 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='book',
            table='Book Details',
        ),
    ]
