# Generated by Django 2.2.3 on 2019-07-18 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0005_book_forsale'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.CharField(default='Novel', max_length=30),
            preserve_default=False,
        ),
    ]
