# Generated by Django 2.2.3 on 2019-07-20 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0006_book_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='availableQuantity',
            field=models.IntegerField(default=4, max_length=3),
            preserve_default=False,
        ),
    ]
