# Generated by Django 2.2.3 on 2019-09-10 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0007_book_availablequantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='availableQuantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='book',
            name='bookId',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='book',
            name='mrp',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='book',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='book',
            name='rating',
            field=models.IntegerField(),
        ),
    ]
