# Generated by Django 2.2.3 on 2019-09-10 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderId', models.CharField(max_length=250)),
                ('orderName', models.CharField(max_length=300)),
                ('email', models.EmailField(max_length=40)),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('img', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'orders',
            },
        ),
    ]
