# Generated by Django 2.2.3 on 2019-09-15 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_cart', '0002_cart_orderdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='status',
            field=models.CharField(default='on order', max_length=300),
            preserve_default=False,
        ),
    ]
